modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/yourusername/create_colonial/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"

[[dependencies.create_colonial]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_colonial]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_colonial]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.j,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_colonial]]
    modId="minecolonies"
    mandatory=true
    versionRange="[1.1.600,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_colonial]]
    modId="structurize"
    mandatory=true
    versionRange="[1.0.700,)"
    ordering="AFTER"
    side="BOTH"
